#!/bin/bash

VIRTUAL_NET=${VIRTUAL_NET:-"openshift"}

# kernel boot args map (node1#args1 node1#args2 node2#args)
KERNEL_BOOT_ARGS_MAP=${KERNEL_BOOT_ARGS_MAP:-}
declare -A kernel_boot_args
for i in $KERNEL_BOOT_ARGS_MAP ; do
  nh=$(echo $i | cut -d '#' -f 1)
  opts=$(echo $i | cut -d '#' -f 2)
  kernel_boot_args[${nh}]="${kernel_boot_args[${nh}]} ${opts}"
done

DNS_DIR="/etc/dnsmasq.d"

MASTER_CPU=${MASTER_CPU:-"4"}
MASTER_MEM=${MASTER_MEM:-"30720"}
WORKER_CPU=${WORKER_CPU:-"4"}
WORKER_MEM=${WORKER_MEM:-"8192"}
BOOTSTRAP_CPU=${BOOTSTRAP_CPU:-"4"}
BOOTSTRAP_MEM=${BOOTSTRAP_MEM:-"16384"}
LOADBALANCER_CPU=${LOADBALANCER_CPU:-"4"}
LOADBALANCER_MEM=${LOADBALANCER_MEM:-"4096"}
AI_CPU=${AI_CPU:-"2"}
AI_MEM=${AI_MEM:-"16384"}

LB_SSH_USER=${LB_SSH_USER:-"root"}
BOOTSTRAP_PORT="1234"

LIBVIRT_DIR="/var/lib/libvirt/images"
LB_IMG_URL="https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
LB_IMAGE="CentOS-7-x86_64-GenericCloud.qcow2"

HUGEPAGES_ENABLED=${HUGEPAGES_ENABLED:-"true"}
BOOTSTRAP_DEFAULT_ADDRESS="192.168.123.102"
