#!/bin/bash

VIRTUAL_NET=${VIRTUAL_NET:-"openshift"}
DNS_DIR="/etc/dnsmasq.d"

declare -A ocp_versions=( ["4.5"]="4.5.21" ["4.6"]="4.6.20" )
OCP_VERSION=${OCP_VERSION:-"${ocp_versions[$OPENSHIFT_VERSION]}"}

declare -A rhcos_versions=( ["4.5"]="4.5/4.5.6" ["4.6"]="4.6/4.6.8" )
RHCOS_VERSION=${RHCOS_VERSION:="${rhcos_versions[$OPENSHIFT_VERSION]}"}

declare -A rhcos_images=( ["4.5"]="rhcos-metal.x86_64.raw.gz" ["4.6"]="rhcos-live-rootfs.x86_64.img" )
RHCOS_IMAGE="${rhcos_images[$OPENSHIFT_VERSION]}"

declare -A rhcos_kernels=( ["4.5"]="rhcos-installer-kernel-x86_64" ["4.6"]="rhcos-live-kernel-x86_64" )
RHCOS_KERNEL="${rhcos_kernels[$OPENSHIFT_VERSION]}"

declare -A rhcos_initramfs=( ["4.5"]="rhcos-installer-initramfs.x86_64.img" ["4.6"]="rhcos-live-initramfs.x86_64.img" )
RHCOS_INITRAMFS="${rhcos_initramfs[$OPENSHIFT_VERSION]}"

declare -A versioned_rootfs_urls=( ["4.5"]="coreos.inst.image_url" ["4.6"]="coreos.live.rootfs_url" )

MASTER_CPU=${MASTER_CPU:-"4"}
MASTER_MEM=${MASTER_MEM:-"24000"}
WORKER_CPU=${WORKER_CPU:-"2"}
WORKER_MEM=${WORKER_MEM:-"8000"}
BOOTSTRAP_CPU=${BOOTSTRAP_CPU:-"4"}
BOOTSTRAP_MEM=${BOOTSTRAP_MEM:-"16000"}
LOADBALANCER_CPU=${LOADBALANCER_CPU:-"1"}
LOADBALANCER_MEM=${LOADBALANCER_MEM:-"1024"}

LB_SSH_USER=${LB_SSH_USER:-"root"}

LIBVIRT_DIR="/var/lib/libvirt/images"
OCP_MIRROR="https://mirror.openshift.com/pub/openshift-v4/clients/ocp"
RHCOS_MIRROR="https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos"
LB_IMG_URL="https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
LB_IMAGE="CentOS-7-x86_64-GenericCloud.qcow2"

HUGEPAGES_ENABLED=${HUGEPAGES_ENABLED:-"true"}
