#!/bin/bash

VIRTUAL_NET=${VIRTUAL_NET:-"openshift"}
DNS_DIR="/etc/dnsmasq.d"

OCP_VERSION=${OCP_VERSION:-"4.5.21"}
RHCOS_VERSION=${RHCOS_VERSION:="4.5/4.5.6"}
RHCOS_IMAGE="rhcos-metal.x86_64.raw.gz"
RHCOS_KERNEL="rhcos-installer-kernel-x86_64"
RHCOS_INITRAMFS="rhcos-installer-initramfs.x86_64.img"
MASTER_CPU=${MASTER_CPU:-"4"}
MASTER_MEM=${MASTER_MEM:-"24000"}
WORKER_CPU=${WORKER_CPU:-"2"}
WORKER_MEM=${WORKER_MEM:-"8000"}
BOOTSTRAP_CPU=${BOOTSTRAP_CPU:-"4"}
BOOTSTRAP_MEM=${BOOTSTRAP_MEM:-"16000"}
LOADBALANCER_CPU=${LOADBALANCER_CPU:-"1"}
LOADBALANCER_MEM=${LOADBALANCER_MEM:-"1024"}

LB_SSH_USER=${LB_SSH_USER:-"root"}

LIBVIRT_DIR="/var/lib/libvirt/images"
OCP_MIRROR="https://mirror.openshift.com/pub/openshift-v4/clients/ocp"
RHCOS_MIRROR="https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos"
LB_IMG_URL="https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
LB_IMAGE="CentOS-7-x86_64-GenericCloud.qcow2"

HUGEPAGES_ENABLED=${HUGEPAGES_ENABLED:-"true"}
