#!/bin/bash
#
# Used environment variables:
#
#   - Hostname
#   - FreeIPAIP
#   - DirectoryManagerPassword
#   - AdminPassword
#   - UndercloudFQDN
#   - FreeIPAExtraArgs: Additional parameters to be passed to FreeIPA script
#
set -eux

source /etc/os-release

[ -n "$AdminPassword" ] || {
    echo "ERROR: AdminPassword env variable must be set"
    exit 1
}
[ -n "$FreeIPAIP" ] || {
    echo "ERROR: FreeIPAIP env variable must be set (provisioning network)"
    exit 1
}

export Hostname=${Hostname:-"$(hostname -f)"}
fqdn=$Hostname
short_name=$(echo $fqdn | cut -d '.' -f1)
export DirectoryManagerPassword=${DirectoryManagerPassword:-"$AdminPassword"}
export FreeIPAExtraArgs=${FreeIPAExtraArgs:-""}
export CLOUD_DOMAIN_NAME=${CLOUD_DOMAIN_NAME:-"$(hostname -d)"}
export FreeIPAIPSubnet=${FreeIPAIPSubnet:-$(ip addr show | grep -o "inet ${FreeIPAIP}/[0-9]* "| cut -d '/' -f2)}
export IPA_IFACE=${IPA_IFACE:-$(ip addr show | grep "inet ${FreeIPAIP}" | awk '{print $(NF)}')}
export DEFAULT_IFACE=${DEFAULT_IFACE:-$(ip route list | grep default | cut -d ' ' -f5)}
export IPA_DNS1=${IPA_DNS1-'8.8.8.8'}
export IPA_DNS2=${IPA_DNS2-'8.8.4.4'}

[ -n "$IPA_IFACE" ] || {
    echo "ERROR: IPA_IFACE env variable is not set and cannot be derived from FreeIPAIP=$FreeIPAIP"
    exit 1
}

if [[ -n "$IPA_IFACE" ]] ; then
    echo "INFO: init NIC $IPA_IFACE"
    cat << EOM > /etc/sysconfig/network-scripts/ifcfg-$IPA_IFACE
# This file is autogenerated by tf-devstack
DEVICE=$IPA_IFACE
ONBOOT=yes
HOTPLUG=no
NM_CONTROLLED=no
BOOTPROTO=static
IPADDR=$FreeIPAIP
PREFIX=$FreeIPAIPSubnet
EOM
    modprobe ipv6 || true
    if [[ "$DEFAULT_IFACE" != "$IPA_IFACE" ]]; then
        ifdown $IPA_IFACE || true
        ifup $IPA_IFACE || true
    fi
fi

if [[ -n "$IPA_DNS1" || -n "$IPA_DNS2" ]] ; then
    echo "INFO: DNS-es $IPA_DNS1 $IPA_DNS2"
    # use 8.8.8.8 as DNS because often local DNSes cannot work like forwarders
    sed -i '/nameserver/d'  /etc/resolv.conf
    if [[ -n "$IPA_DNS1" ]] ; then
        cat <<EOF | sudo tee -a /etc/resolv.conf
nameserver $IPA_DNS1
EOF
    fi
    if [[ -n "$IPA_DNS2" ]] ; then
        cat <<EOF | sudo tee -a /etc/resolv.conf
nameserver $IPA_DNS2
EOF
    fi
fi

yum -y remove openstack-dashboard
if [[ $VERSION_ID == 7* ]]; then
    # [cloud-user@rhosp13-ipa-13624 ~]$ yum repolist all
    # Failed to set locale, defaulting to C
    # Loaded plugins: search-disabled-repos
    # repo id         repo name     status
    # !epel           epel          disabled
    epel_repo=$(yum repolist all| awk  '/epel/{print($1)}' | cut -d '/' -f1 | head -n 1 | tr -d '!')
    if [ -z "$epel_repo" ] ; then
        wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum localinstall -y epel-release-latest-7.noarch.rpm
        for i in {1..3} ; do
            epel_repo=$(yum repolist | awk '/epel/{print($1)}' | cut -d '/' -f1 | head -n 1 | tr -d '!')
            [ -n "$epel_repo" ] && break
        done
    fi
    if [ -z "$epel_repo" ] ; then
        echo "ERROR: epel repo is not available"
        exit 1
    fi
    yum update -y
    yum install -y --enablerepo=$epel_repo rng-tools git ipa-server ipa-server-dns python-novajoin mod_nss haveged
else
    # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/installing_identity_management/index
    yum module disable -y idm
    yum module enable -y idm:DL1
    yum -y distro-sync
    yum update -y
    yum module install -y idm:DL1/{dns,client}
    yum install -y iptables rng-tools git python3-novajoin
    #Fix for SSL VERSION ISSUE https://access.redhat.com/solutions/5527751
    dnf downgrade -y java-1.8.0-openjdk java-1.8.0-openjdk-headless
fi

# Set iptables rules
cat << EOF > freeipa-iptables-rules.txt
# Firewall configuration written by system-config-firewall
# Manual customization of this file is not recommended.
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
#TCP ports for FreeIPA
-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 443  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 389 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 636 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 88  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 464  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 53  -j ACCEPT
#UDP ports for FreeIPA
-A INPUT -m state --state NEW -m udp -p udp --dport 88 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 464 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF

iptables-restore < freeipa-iptables-rules.txt

if [[ $VERSION_ID != 8* ]]; then
   chkconfig haveged on
   systemctl start haveged

   # Remove conflicting httpd configuration
   rm -f /etc/httpd/conf.d/ssl.conf
fi


function install_ipa_server() {
    ipa-server-install -U --uninstall || true

    # Set up FreeIPA
    local res=0
    ipa-server-install -U -r `hostname -d|tr "[a-z]" "[A-Z]"` \
                    -p $DirectoryManagerPassword -a $AdminPassword \
                    --hostname $fqdn \
                    --ip-address=$FreeIPAIP \
                    --setup-dns --auto-forwarders --auto-reverse $FreeIPAExtraArgs || res=1
    return $res
}

#Adding ipaserver fqdn to the /etc/hosts
sed -i /etc/hosts -e "s/^$FreeIPAIP.*$/$FreeIPAIP $fqdn $short_name/"

for i in {1..5} ; do
    if install_ipa_server ; then
        break
    fi
done

# https://bugzilla.redhat.com/show_bug.cgi?id=1571897
## * Set CA to create CRL on restart
sed -i "s/ca.crl.MasterCRL.publishOnStart=.*/ca.crl.MasterCRL.publishOnStart=true/" /etc/pki/pki-tomcat/ca/CS.cfg
systemctl restart pki-tomcatd@pki-tomcat.service
#

# wait a bit after pki restart
sleep 10
