
#RHEL8 undercloud install

#removing docker-ce package to avoid conflicts with podman
dnf remove -y docker-ce-cli || true

dnf install -y python3-tripleoclient rhosp-director-images rhosp-director-images-ipa

if [[ -n "$ENABLE_TLS" ]] ; then
  # WA for TLS
  #   To avoid error:
  #     ipa-getkeytab -s rhosp16-ipa-20.dev.localdomain -p nova/rhosp16-undercloud-20.dev.localdomain -k /etc/novajoin/krb5.keytab
  #     Failed to add key to the keytab
  mkdir -p /etc/novajoin
  #   To avoid error with domain resolving
  cat <<EOF > /etc/resolv.conf
# Generated by tf-devstack
search ${domain}
nameserver $ipa_prov_ip
EOF

  # Up eth1 with address in  prov network.
  # undercloud install connects to IPA before it setups br-ctlplane 
  cat << EOM > /etc/sysconfig/network-scripts/ifcfg-eth1
# This file is autogenerated by tf-devstack
DEVICE=eth1
ONBOOT=no
HOTPLUG=no
NM_CONTROLLED=no
BOOTPROTO=none
IPADDR=$prov_ip
NETMASK=255.255.255.0
EOM
  modprobe ipv6 || true
  ifdown eth1
  ifup eth1
fi
