
#removing docker-ce package to avoid conflicts with podman
sudo dnf remove -y docker-ce-cli || true

if [[ "$ENABLE_RHEL_REGISTRATION" == 'true' ]] ; then
  # fix module otherwise upstream usage leads to packages conflicts
  sudo dnf module disable -y container-tools:rhel8
  sudo dnf module enable -y container-tools:2.0
  sudo dnf distro-sync -y 
fi

pkgs="python3-tripleoclient rhosp-director-images rhosp-director-images-ipa"
[[ -z "$overcloud_ceph_instance" ]] || pkgs+=" ceph-ansible"
sudo dnf install -y $pkgs

if [[ -n "$ENABLE_TLS" ]] ; then
  # WA for TLS
  #   To avoid error:
  #     ipa-getkeytab -s rhosp16-ipa-20.dev.localdomain -p nova/rhosp16-undercloud-20.dev.localdomain -k /etc/novajoin/krb5.keytab
  #     Failed to add key to the keytab
  sudo mkdir -p /etc/novajoin
  #   To avoid error with domain resolving 
  cat << EOF | sudo tee /etc/resolv.conf 
# Generated by tf-devstack
search ${domain}
nameserver $ipa_prov_ip
EOF

  # Up eth1 with address in  prov network.
  # undercloud install connects to IPA before it setups br-ctlplane 
  cat << EOF | sudo tee /etc/sysconfig/network-scripts/ifcfg-eth1
# This file is autogenerated by tf-devstack
DEVICE=eth1
ONBOOT=no
HOTPLUG=no
NM_CONTROLLED=no
BOOTPROTO=none
IPADDR=$prov_ip
NETMASK=255.255.255.0
EOF
  sudo modprobe ipv6 || true
  sudo ifdown eth1
  sudo ifup eth1
fi

#RHEL8 undercloud install
if [[ -n "$RHEL_USER" ]]; then
  export rhsm_image_registry_credentials="
  ContainerImageRegistryCredentials:
    ${OPENSTACK_CONTAINER_REGISTRY}:
      ${RHEL_USER}: '${RHEL_PASSWORD}'"
fi

if [[ -n "$overcloud_ceph_instance" ]] ; then
  tmpl=containers-prepare-parameter-ceph.yaml.template
else
  tmpl=containers-prepare-parameter.yaml.template
fi
cat $my_dir/$tmpl | envsubst >~/containers-prepare-parameter.yaml
echo "INFO: containers-prepare-parameter.yaml"
cat ~/containers-prepare-parameter.yaml

cat $my_dir/${RHOSP_VERSION}_undercloud.conf.template | envsubst >~/undercloud.conf
echo "INFO: undercloud.conf"
cat ~/undercloud.conf

cd
openstack undercloud install
