#!/bin/bash -e

my_file="$(readlink -e "$0")"
my_dir="$(dirname $my_file)"

cd
source rhosp-environment.sh
source $my_dir/../../common/common.sh
source $my_dir/../providers/common/common.sh
source $my_dir/../providers/common/functions.sh


if [[ "$ENABLE_TLS" == 'ipa' ]] ; then
  export undercloud_nameservers="$ipa_prov_ip"
  export nova_join_option="enable_novajoin = True"
  export ipa_otp_option="ipa_otp = \"$OTP_PASSWORD\""
else
  export undercloud_nameservers=${NAMESERVER_LIST:-"8.8.8.8"}
  export nova_join_option=""
  export ipa_otp_option=""
fi

export ceph_option=""
if [[ -n "$overcloud_ceph_instance" ]]; then
    export ceph_option="clean_nodes=true"
fi

if [[ "$ENABLE_TLS" == 'ipa' ]] ; then
  # WA for TLS
  #   To avoid error:
  #     ipa-getkeytab -s rhosp16-ipa-20.dev.clouddomain -p nova/rhosp16-undercloud-20.dev.clouddomain -k /etc/novajoin/krb5.keytab
  #     Failed to add key to the keytab
  sudo mkdir -p /etc/novajoin
  old_ns=$(grep 'nameserver ' /etc/resolv.conf)
    #   To avoid error with domain resolving
  cat << EOF | sudo tee /etc/resolv.conf
# Generated by tf-devstack
search ${domain}
nameserver $ipa_prov_ip
# during UC deploy it resets ctlplane interface and yum operations fail in rhel subscription case
$old_ns
EOF

  # WA: in unknown reason eth1 is reset at this step
  sudo ip addr show
  sudo ip link set up dev $undercloud_local_interface
  sudo ip addr replace ${prov_ip}/${prov_subnet_len} dev $undercloud_local_interface
  sudo ip addr show
fi

export local_mtu=`/sbin/ip link show $undercloud_local_interface | grep -o "mtu.*" | awk '{print $2}'`

#configure_registries must be running twice because undercloud_deploy updates registries.conf
source $my_dir/${RHOSP_MAJOR_VERSION}_configure_registries_undercloud.sh
source $my_dir/${RHOSP_MAJOR_VERSION}_undercloud_deploy.sh
source $my_dir/${RHOSP_MAJOR_VERSION}_configure_registries_undercloud.sh
