#!/bin/bash
#
# Used environment variables:
#
#   - Hostname
#   - FreeIPAIP
#   - DirectoryManagerPassword
#   - AdminPassword
#   - UndercloudFQDN
#   - FreeIPAExtraArgs: Additional parameters to be passed to FreeIPA script
#
set -eux

source /etc/os-release

export Hostname=${Hostname:-"${ipa_instance}.${domain}"}
export FreeIPAIP=${FreeIPAIP:-"${ipa_prov_ip}"}
export DirectoryManagerPassword=${DirectoryManagerPassword:-"$IPMI_PASSWORD"}
export AdminPassword=${AdminPassword:-"$IPMI_PASSWORD"}
export UndercloudFQDN=${UndercloudFQDN:-"${undercloud_instance}.${domain}"}
export FreeIPAExtraArgs=${FreeIPAExtraArgs:-""}
export CLOUD_DOMAIN_NAME=${CLOUD_DOMAIN_NAME:-"${domain}"}

cat << EOM > /etc/sysconfig/network-scripts/ifcfg-eth1
# This file is autogenerated by tf-devstack
DEVICE=eth1
ONBOOT=yes
HOTPLUG=no
NM_CONTROLLED=no
BOOTPROTO=static
IPADDR=$ipa_prov_ip
NETMASK=255.255.255.0
EOM
modprobe ipv6
ifdown eth1
ifup eth1

yum -y remove openstack-dashboard
yum update -y

PKGS="ipa-server ipa-server-dns rng-tools git python-novajoin"
yum_opts="-y"
if [[ $VERSION_ID == 7* ]]; then
    PKGS+=" mod_nss haveged"
    epel_repo=$(yum repolist all| awk  '/epel/{print($1)}')
    if [ -z "$epel_repo" ] ; then
        yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        epel_repo=$(yum repolist | awk '/epel/{print($1)}')
    fi
    if [ -z "$epel_repo" ] ; then
        echo "ERROR: epel repo is not available"
        exit 1
    fi
    yum_opts+=" --enablerepo=epel*"
fi
yum install $yum_opts $PKGS

# Set iptables rules
cat << EOF > freeipa-iptables-rules.txt
# Firewall configuration written by system-config-firewall
# Manual customization of this file is not recommended.
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
#TCP ports for FreeIPA
-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 443  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 389 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 636 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 88  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 464  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 53  -j ACCEPT
#UDP ports for FreeIPA
-A INPUT -m state --state NEW -m udp -p udp --dport 88 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 464 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF

iptables-restore < freeipa-iptables-rules.txt

if [[ $VERSION_ID != 8* ]]; then
   chkconfig haveged on
   systemctl start haveged

   # Remove conflicting httpd configuration
   rm -f /etc/httpd/conf.d/ssl.conf
fi

# Set up FreeIPA
ipa-server-install -U -r `hostname -d|tr "[a-z]" "[A-Z]"` \
                   -p $DirectoryManagerPassword -a $AdminPassword \
                   --hostname `hostname -f` \
                   --ip-address=$FreeIPAIP \
                   --setup-dns --auto-forwarders --auto-reverse $FreeIPAExtraArgs

# Authenticate
echo $AdminPassword | kinit admin

# Verify we have TGT
klist

# Precreate undercloud entry and generate OTP
otp=$(novajoin-ipa-setup \
    --principal admin \
    --password "$AdminPassword" \
    --server `hostname -f` \
    --realm ${CLOUD_DOMAIN_NAME^^} \
    --domain ${CLOUD_DOMAIN_NAME} \
    --hostname ${UndercloudFQDN} \
    --precreate)

echo $otp > ~/undercloud_otp

if [ "$?" = '1' ]; then
    exit 1
fi
