#!/bin/bash
#
# Used environment variables:
#
#   - Hostname
#   - FreeIPAIP
#   - DirectoryManagerPassword
#   - AdminPassword
#   - UndercloudFQDN
#   - FreeIPAExtraArgs: Additional parameters to be passed to FreeIPA script
#
set -eux

source /etc/os-release

[ -n "$UndercloudFQDN" ] || {
    echo "ERROR: UndercloudFQDN env variable must be set"
    exit 1
}
[ -n "$AdminPassword" ] || {
    echo "ERROR: AdminPassword env variable must be set"
    exit 1
}
[ -n "$FreeIPAIP" ] || {
    echo "ERROR: FreeIPAIP env variable must be set (provisioning network eth1)"
    exit 1
}

fqdn=$(hostname -f)
domain=$(hostname -d)
export Hostname=${Hostname:-"${fqdn}"}
export DirectoryManagerPassword=${DirectoryManagerPassword:-"$AdminPassword"}
export FreeIPAExtraArgs=${FreeIPAExtraArgs:-""}
export CLOUD_DOMAIN_NAME=${CLOUD_DOMAIN_NAME:-"${domain}"}

cat << EOM > /etc/sysconfig/network-scripts/ifcfg-eth1
# This file is autogenerated by tf-devstack
DEVICE=eth1
ONBOOT=yes
HOTPLUG=no
NM_CONTROLLED=no
BOOTPROTO=static
IPADDR=$FreeIPAIP
NETMASK=255.255.255.0
EOM
modprobe ipv6
ifdown eth1
ifup eth1

yum -y remove openstack-dashboard
yum update -y

yum install -y rng-tools git
if [[ $VERSION_ID == 7* ]]; then
    epel_repo=$(yum repolist all| awk  '/epel/{print($1)}' | cut -d '/' -f1 | head -n 1)
    if [ -z "$epel_repo" ] ; then
        wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum localinstall -y epel-release-latest-7.noarch.rpm
        for i in {1..3} ; do 
            epel_repo=$(yum repolist | awk '/epel/{print($1)}' | cut -d '/' -f1 | head -n 1)
            [ -n "$epel_repo" ] && break
        done
    fi
    if [ -z "$epel_repo" ] ; then
        echo "ERROR: epel repo is not available"
        exit 1
    fi
    yum install -y --enablerepo=$epel_repo ipa-server ipa-server-dns python-novajoin mod_nss haveged
else
    # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/installing_identity_management/index
    yum module enable -y idm:DL1
    yum -y distro-sync
    yum module install -y idm:DL1/{dns,client}
    yum install -y python3-novajoin
fi

# Set iptables rules
cat << EOF > freeipa-iptables-rules.txt
# Firewall configuration written by system-config-firewall
# Manual customization of this file is not recommended.
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
#TCP ports for FreeIPA
-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 443  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 389 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 636 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 88  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 464  -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 53  -j ACCEPT
#UDP ports for FreeIPA
-A INPUT -m state --state NEW -m udp -p udp --dport 88 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 464 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF

iptables-restore < freeipa-iptables-rules.txt

if [[ $VERSION_ID != 8* ]]; then
   chkconfig haveged on
   systemctl start haveged

   # Remove conflicting httpd configuration
   rm -f /etc/httpd/conf.d/ssl.conf
fi

# Set up FreeIPA
ipa-server-install -U -r `hostname -d|tr "[a-z]" "[A-Z]"` \
                   -p $DirectoryManagerPassword -a $AdminPassword \
                   --hostname `hostname -f` \
                   --ip-address=$FreeIPAIP \
                   --setup-dns --auto-forwarders --auto-reverse $FreeIPAExtraArgs


# https://bugzilla.redhat.com/show_bug.cgi?id=1571897
## * Set CA to create CRL on restart
sed -i "s/ca.crl.MasterCRL.publishOnStart=.*/ca.crl.MasterCRL.publishOnStart=true/" /etc/pki/pki-tomcat/ca/CS.cfg
systemctl restart pki-tomcatd@pki-tomcat.service
#

# Authenticate
echo $AdminPassword | kinit admin

# Verify we have TGT
klist

# Precreate undercloud entry and generate OTP
otp=$(novajoin-ipa-setup \
    --principal admin \
    --password "$AdminPassword" \
    --server `hostname -f` \
    --realm ${CLOUD_DOMAIN_NAME^^} \
    --domain ${CLOUD_DOMAIN_NAME} \
    --hostname ${UndercloudFQDN} \
    --precreate)

echo $otp > ~/undercloud_otp

if [ "$?" = '1' ]; then
    exit 1
fi
